"""create center operating hours table

Revision ID: f1f5ee6528a8
Revises: 2bb3eb425376
Create Date: 2026-08-09 17:02:11.805784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f5ee6528a8'
down_revision: Union[str, Sequence[str], None] = '2bb3eb425376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('center_operating_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['collection_centers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('center_id', 'day_of_week', name='unique_center_day_operating_hour')
    )
    op.create_index(op.f('ix_center_operating_hours_id'), 'center_operating_hours', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_center_operating_hours_id'), table_name='center_operating_hours')
    op.drop_table('center_operating_hours')
    # ### end Alembic commands ###
