"""add recent center views and search history tables

Revision ID: 15d090863fce
Revises: b82a886328a3
Create Date: 2026-08-09 18:33:37.707106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d090863fce'
down_revision: Union[str, Sequence[str], None] = 'b82a886328a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recent_center_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['collection_centers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'center_id', name='unique_user_center_view')
    )
    op.create_index(op.f('ix_recent_center_views_center_id'), 'recent_center_views', ['center_id'], unique=False)
    op.create_index(op.f('ix_recent_center_views_id'), 'recent_center_views', ['id'], unique=False)
    op.create_index(op.f('ix_recent_center_views_user_id'), 'recent_center_views', ['user_id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('search_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_id'), 'search_history', ['id'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_id'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_recent_center_views_user_id'), table_name='recent_center_views')
    op.drop_index(op.f('ix_recent_center_views_id'), table_name='recent_center_views')
    op.drop_index(op.f('ix_recent_center_views_center_id'), table_name='recent_center_views')
    op.drop_table('recent_center_views')
    # ### end Alembic commands ###
