"""create recycling activities table

Revision ID: b82a886328a3
Revises: f1f5ee6528a8
Create Date: 2026-08-09 17:50:50.481642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82a886328a3'
down_revision: Union[str, Sequence[str], None] = 'f1f5ee6528a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recycling_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('waste_category_id', sa.Integer(), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('recycled_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waste_category_id'], ['waste_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recycling_activities_id'), 'recycling_activities', ['id'], unique=False)
    op.create_index(op.f('ix_recycling_activities_user_id'), 'recycling_activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recycling_activities_user_id'), table_name='recycling_activities')
    op.drop_index(op.f('ix_recycling_activities_id'), table_name='recycling_activities')
    op.drop_table('recycling_activities')
    # ### end Alembic commands ###
